---
version: "3"

services:

  postgres:
    environment:
      POSTGRES_PASSWORD: # <- A long, multi-word passphrase is best.

  rails:
    environment:
      POSTGRES_PASSWORD: # <- A long, multi-word passphrase is best.
      RAILS_ENV: development
      DEVISE_JWT_SECRET_KEY: # <- Generate one with `bundle exec rake secret`. Change this string to invalidate JWTs.
    tty: true
    stdin_open: true
      # Above: These 2 lines let us work with the REPL we get from binding.pry.
      # It is useful in development and unnecessary in production.
      # Attach to the container using `docker attach`,
      # and it will be like `rails server` is running on your machine outside a container.

  jobs:
    environment:
      POSTGRES_PASSWORD: # <- A long, multi-word passphrase is best.
      RAILS_ENV: development
      DEVISE_JWT_SECRET_KEY: # <- Generate one with `bundle exec rake secret`. Change this string to invalidate JWTs.
    tty: true
    stdin_open: true
      # Above: These 2 lines let us work with the REPL we get from binding.pry.
      # It is useful in development and unnecessary in production.
      # Attach to the container using `docker attach`,
      # and it will be like `rails server` is running on your machine outside a container.

  webpack-dev-server:
    container_name: unfunded-requirements-webpack-dev-server
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "3035:3035"
    environment:
      NODE_PATH: "/app/node_modules:/usr/lib/nodejs"
    tty: true
    stdin_open: true
    command: "dumb-init -- /app/bin/webpack-dev-server"
