---
version: "3"

volumes:

  postgres_data:

services:

  postgres:
    container_name: flagship-rails-postgres
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: flagship-rails-redis
    image: "redis:6"

  #mailcatcher: TODO!

  rails:
    container_name: flagship-rails-rails
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      NODE_PATH: "/app/node_modules:/usr/lib/nodejs"

  jobs:
    container_name: flagship-rails-jobs
    build:
      context: .
      dockerfile: docker/jobs/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379
      NODE_PATH: "/app/node_modules:/usr/lib/nodejs"
