#!/usr/bin/env ruby

YELLOW="\e[33m"
GREEN="\e[32m"
MAGENTA="\e[35m"
TEAL="\e[36m"
END_COLOR="\e[0m"

def run(cmd)
  full_cmd = "umask 002 && #{cmd}"
  puts "Running #{TEAL}#{full_cmd}#{END_COLOR}"
  exit($?.exitstatus) unless system full_cmd
end

####

puts "#{YELLOW}restarting containers...#{END_COLOR}"
services_to_restart = %w{rails jobs}
run "docker-compose stop #{services_to_restart} ; docker-compose up -d --no-deps #{services_to_restart.join(' ')}"
puts
puts "Removing dangling images..."
run 'docker rmi $(docker images -q -f "dangling=true"); true'
puts "#{GREEN}Any dangling images have been removed. docker-rmi errors can be ignored.#{END_COLOR}"

####

puts
puts "#{GREEN}Services restarted! Status:#{END_COLOR}\n"
print `docker ps -a`
