default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: flagship_rails_development

test:
  <<: *default
  database: flagship_rails_test

production:
  <<: *default
  database: flagship_rails_production
